#!/bin/sh

set -e

# Default values
SERVERNET="192.168.42.42/30"
DHCP_RANGE="192.168.42.41,192.168.42.41"

if test -r "/etc/specific/usb_gadget.conf"; then
 . "/etc/specific/usb_gadget.conf"
fi

if test -z "$INTERFACE" || test -z "$ACTION"; then
  echo "Script must be called by udev"
  exit 1
fi
IFNAME="$INTERFACE"
SERVER=${SERVERNET%%/*}
DNSMASQ="/var/run/dnsmasq/dnsmasq_gadget.conf"
DOMAIN="local"
TYPE="normal"

grep -vq " production " /proc/cmdline || TYPE="production"
mkdir -p "/var/run/dnsmasq"

usb_gadget_stop()
{
  ip link set down dev "$IFNAME" || :
  ip address flush dev "$IFNAME" || :
  : > "$DNSMASQ"
  /etc/init.d/dnsmasq update
}

usb_gadget_as_server()
{
  usb_gadget_stop
  cat > "$DNSMASQ".tmp << EOF
domain-needed
bogus-priv
no-resolv
no-poll
local=/${DOMAIN}/
expand-hosts
domain=${DOMAIN}
dhcp-option=3
dhcp-option=6
dhcp-range=${DHCP_RANGE},1h
interface=$IFNAME
EOF
  mv "$DNSMASQ".tmp "$DNSMASQ"
  ip address add "$SERVERNET" dev "$IFNAME"
  ip link set up dev "$IFNAME"
  /etc/init.d/dnsmasq update
}

usb_gadget_as_client()
{
  usb_gadget_stop
  ip link set up dev "$IFNAME"
  udhcpc -Sbi "$IFNAME"
}

case "${ACTION}:${TYPE}" in
  add:production) usb_gadget_as_client ;;
  add:*)          usb_gadget_as_server ;;
  remove:*)       usb_gadget_stop ;;
esac
