#!/bin/sh
#
# detect_hw_variant 
#

#
# detect_hw_variant makes product-specific settings
# (i.e. hiding serial port settings in wbm/cbm on devices
# w/o a serial port)
#

function SetWBMConfig
{
    echo -n "Setting WBM configuration to "

    local product=$(/etc/config-tools/get_typelabel_value DEVCONF)
    local org_file=""
    local link="/var/www/wbm/frontend_config_wbm.xml"
    local order=$(/etc/config-tools/get_typelabel_value ORDER | awk -F/ '{print $1}')
    
    if [ -n "$order" ]
    then   
      # suborder number (example value: 0000-0100)
      local subOrder=$(/etc/config-tools/get_typelabel_value ORDER | awk -F/ '{print $2}')
     
      # suborder number exists?
      if [ -n "$subOrder" ]
      then
          # check that file exists
          if [ -f /var/www/wbm/xml/${order}_${subOrder}_wbm.xml ]
          then 
              # use full order number ('/' = '_')
              order=$(printf "%s_%s" $order $subOrder)
          fi
      fi
      
      org_file=/var/www/wbm/xml/${order}_wbm.xml
      echo "${order}"

    else
      org_file=/var/www/wbm/xml/750-8206_wbm.xml
      echo "DEFAULT (750-8206)"
    fi


    #only write a new config-file if it differs
    if [ -e $link ]; then
      #use readlink to get the linked file
      local file=`readlink $link`
      if [ $file == $org_file ]; then
        return 0;
      fi
    fi

    ln -fs $org_file $link
}

case $1 in

  start)
    SetWBMConfig
  ;;
esac
